language: php

php:
  - '7.4'
  - '8.0'
  - '8.1'
  - '8.2'
  - '8.3'
  - '8.4'
  - '8.5'

before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email:
    recipients:
      - contact@geminorum.ir
    on_success: never
    on_failure: always
